### ISSUE TITLE
USER STORY - SETUP WITH SUPERUSER

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#1]
As a **backend developer** I can **login and out of my superuser account** so that I can **test my APIs and authorisations**.

**EPIC**
- Backend Initial Setup

**Tasks:**
- [x] Create GitHub Account
- [x] Create Django project
- [x] Install requirements
- [x] Create a superuser

**Acceptance Criteria:**
- [x] Login and out as superuser
