### ISSUE TITLE
USER STORY - PROFILE FILTERING

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#10]
As a **frontend developer** I can **filter the profile API** so that **I can develop the frontend to allow users to search profiles based on specific criteria**.

**EPIC**
- API Filtering

**Tasks:**
Build in filter_backends for:
- [x] filtering
- [x] ordering

Build in filterset_fields to identify profiles by:
- [x] following
- [x] followed
- [x] languages known by user

Build in ordering_fields to order profiles by:
- [x] no. of articles
- [x] no. of followers
- [x] no. of those following the user
- [x] date user followed others
- [x] date other followed the user

**Acceptance Criteria:**
- [x] Filter provides expected results
- [x] Ordering provides expected results
