### ISSUE TITLE
USER STORY - ARTICLE FILTERING

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#11]
As a **frontend developer** I can **filter the article API** so that **I can develop the frontend to allow users to search articles based on specific criteria**.

**EPIC**
- API Filtering

**Tasks:**
Build in filter_backends for:
- [x] searching
- [x] filtering
- [x] ordering

Build in search_fields to identify articles by:
- [x] username
- [x] article title

Build in filterset_fields to identify articles by:
- [x] following
- [x] followed
- [x] profile
- [x] language in article

Build in ordering_fields to order articles by:
- [x] no. of comments
- [x] no. of likes

**Acceptance Criteria:**
- [x] Search provides expected results
- [x] Filter provides expected results
- [x] Ordering provides expected results
