### ISSUE TITLE
USER STORY - DEPLOYMENT

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#14]
As a **frontend developer** I can **access the live API** so that **I can link it with the frontend application**.

**EPIC**
- Live Deployment

**Tasks:**
- [x] JWT tokens and dj_rest_authorisation setup
- [x] Live Database setup
- [x] Heroku setup and linked to AWS and live Database

**Acceptance Criteria:**
- [x] Test registration, login and logout via frontend
- [x] confirm JWT tokens obtained and refreshing as expected
- [x] test file/image upload via frontend as expected
- [x] check api data retrieval via frontend as expected
- [x] check api data create via frontend as expected
- [x] check api data update via frontend as expected
- [x] check api data delete via frontend as expected
