### ISSUE TITLE
USER STORY - API DOCUMENTATION

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#15]
As a **frontend developer** I can **view and test the available endpoints provided via the documentation** so that **I can clarify the appropriate endpoints for axios requests**.

**EPIC**
- API Build

**Tasks:**
- [x] Create API schema
- [x] Build API Document Interface

**Acceptance Criteria:**
- [x] Confirm API Doc Interaction works for GET, POST, PUT, DELETE
- [x] Confirm Doc Interaction accounts for authorisation levels
