### ISSUE TITLE
USER STORY: LIST RECOMMENDATIONS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#16]
As a **frontend developer** I can **access the recommendations list endpoint information in a user’s profile endpoint** so that **I can use the data to enhance the profile pages.**

**EPIC**

API Build

**Tasks:**

- [x] Model
- [x] View - Received recommendation list view
- [x] Serializer - Received recommendation serializer
- [x] URL - list

**Acceptance Criteria:**

- [x] API accessible via URL
- [x] Recommended articles relevant to assigned profile
