### ISSUE TITLE
USER STORY: RECOMMEND ARTICLES

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#17]
As a **frontend developer** I can **access the recommendations add endpoint** so that **I can allow users to recommend articles to other users.**

**EPIC**

API Build

**Tasks:**

- [x] View - Recommended article view
- [x] Serializer - Recommended article serializer
- [x] URL - add

**Acceptance Criteria:**

- [x] API accessible via URL
- [x] Recommended article adds as expected
