### ISSUE TITLE
USER STORY: REMOVE RECOMMENDATIONS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#18]
As a **frontend developer** I can **access the recommendations delete endpoint** so that **I can allow the recipient of a recommendation to remove it from their list.**

**EPIC**

API Build

**Tasks:**

- [x] View – Delete recommendation view
- [x] Permission - IsRecipientOrReadOnly
- [x] URL - delete

**Acceptance Criteria:**

- [x] API accessible via URL
- [x] Only the recipient can delete recommendations
