### ISSUE TITLE
USER STORY: LIST LINKS

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#19]
As a **frontend developer** I can **access the links endpoint information for a specific article** so that **I can use the data to enhance the article page.**

**EPIC**

API Build

**Tasks:**

- [x] Model
- [x] View - Links list view for article
- [x] Serializer - Links serializer for article
- [x] URL - list

**Acceptance Criteria:**

- [x] API accessible via URL
- [x] Links relevant to article presented
