### ISSUE TITLE
USER STORY - AWS SETUP

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#2]
As a **frontend developer** I can **store and access all user uploaded files and images via AWS** so that **I can access them in my frontend design**.

**EPIC**
- Backend Initial Setup

**Tasks:**
- [x] Set up an S3 account
- [x] Set the appropriate permissions
- [x] Set up an IAM user with appropriate authorisation levels
- [x] Set up the AWS in the Django settings and env files.

**Acceptance Criteria:**
- [x] Upload via backend to test connection
- [x] Tested in frontend
