### ISSUE TITLE
USER STORY: LINKS DELETE

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#21]
As a **frontend developer** I can **access the links delete endpoint** so that **I can allow users to remove links they no longer want to be associated with their article.**

**EPIC**

API Build

**Tasks:**

- [x] View – detail view
- [x] Serializer – detail serializer

**Acceptance Criteria:**

- [x] API accessible via URL
- [x] Links deleted as expected
