### ISSUE TITLE
USER STORY - PROFILE ENDPOINT

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#4]
As a **frontend developer** I can **access profile endpoints** so that **I can use the data to build profile pages**.

**EPIC**
- API Build

**Tasks:**
- [x] Model (Signal to auto generate on user registration)
- [x] Views (List and Detail)
- [x] URLS (List and Detail)
- [x] Serializer for all

**Acceptance Criteria:**
- [x] API accessible via URL
- [x] Agreed endpoints detailed
