### ISSUE TITLE
USER STORY - LANGUAGE ENDPOINT

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#5]
As a **frontend developer** I can **access language endpoints** so that **I can use the data to enhance the profile pages**.

**EPIC**
- API Build

**Tasks:**
- [x] Choices file for reusable dropdown options
- [x] Model
- [x] Views X 2 (List and Detail)
- [x] URLS X 2 (List and Detail)
- [x] Serializer X 2 (Detail inherits from LanguageSerializer to change language to Read Only.

**Acceptance Criteria:**
- [x] API accessible via URL
- [x] Agreed endpoints detailed
