### ISSUE TITLE
USER STORY - ARTICLE ENDPOINT

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#6]
As a **frontend developer** I can **access article endpoints** so that **I can use the data to build main article feed pages**.

**EPIC**
- API Build

**Tasks:**
- [x] Model
- [x] Views X 2 (List and Detail)
- [x] URLS X 2 (List and Detail)
- [x] Serializer for all

**Acceptance Criteria:**
- [x] API accessible via URL
- [x] Agreed endpoints detailed
