### ISSUE TITLE
USER STORY - COMMENT ENDPOINT

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#7]
As a **frontend developer** I can **access comment endpoints** so that **I can use the data to build comments related to the articles**.

**EPIC**
- API Build

**Tasks:**
- [x] Model
- [x] Views X 2 (List and Detail)
- [x] URLS X 2 (List and Detail)
- [x] Serializer X 2 (Detail inherits from CommentSerializer to change article to Read Only souring article.id.

**Acceptance Criteria:**
- [x] API accessible via URL
- [x] Agreed endpoints detailed
