### ISSUE TITLE
USER STORY - LIKE ENDPOINT

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/BitWise-DRF#8]
As a **frontend developer** I can **access like endpoints** so that **I can use the data to like articles**.

**EPIC**
- API Build

**Tasks:**
- [x] Model
- [x] Views X 2 (List and Detail)
- [x] URLS X 2 (List and Detail)
- [x] Serializer for all

**Acceptance Criteria:**
- [x] API accessible via URL
- [x] Agreed endpoints detailed
